### ISSUE TITLE
[Bug]: It literallly crashes when it caches

### ISSUE THREAD

**Issue by ArdoDev-stupid** [ThePlank/PlankEngine#2]
### It doesn't cache

![image](https://user-images.githubusercontent.com/98959759/176598496-332319b8-7ad4-46e5-9195-e9288d5bf378.png)

### Are you modding a build from source, with HScript or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I literally did not change anything in the caching system

**Comment by ThePlank** [comment]
fixed it









































cum

**Comment by ArdoDev-stupid** [comment]
fuck you

**Comment by ThePlank** [comment]
ehhh. not going to fix it....


there is a jar of cum under your kitchen sink :/

**Comment by ArdoDev-stupid** [comment]
shit you
